# Generated by Django 4.2.3 on 2023-08-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_route_object_3d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object_3d',
            old_name='dotscol',
            new_name='dotsCol',
        ),
    ]
