# Generated by Django 4.2.3 on 2023-08-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_object_3d_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_3d',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
