# Generated by Django 4.2.3 on 2023-12-25 01:53

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_object_3d_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='initialObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ply_file', models.FileField(upload_to='ply')),
                ('camera_image', models.ImageField(upload_to=mainapp.models.camera_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
