# Generated by Django 4.2.3 on 2023-12-25 01:59

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_initialobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialobject',
            name='camera_image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.camera_image_path),
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='ply_file',
            field=models.FileField(blank=True, null=True, upload_to='ply'),
        ),
    ]
