# Generated by Django 4.2.3 on 2023-12-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_initialobject_camera_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialobject',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2023/12/25 10:49:38', max_length=255),
        ),
    ]
