# Generated by Django 4.2.3 on 2023-12-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_initialobject_is_finished_alter_initialobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2023/12/25 11:53:18', max_length=255),
        ),
    ]
