# Generated by Django 4.2.3 on 2023-12-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_initialobject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialobject',
            name='camera_image',
        ),
        migrations.RemoveField(
            model_name='initialobject',
            name='ply_file',
        ),
        migrations.AddField(
            model_name='initialobject',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='initialobject',
            name='ply_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2023/12/26 16:44:34', max_length=255),
        ),
    ]
