# Generated by Django 4.2.3 on 2023-12-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_initialobject_camera_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialobject',
            name='is_pined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2023/12/28 11:49:50', max_length=255),
        ),
    ]
