# Generated by Django 4.2.3 on 2023-12-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_initialobject_is_selected_alter_initialobject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialobject',
            old_name='is_pined',
            new_name='is_pinned',
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2023/12/29 15:29:27', max_length=255),
        ),
    ]
