# Generated by Django 4.2.3 on 2023-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_rename_is_pined_initialobject_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_3d',
            name='initial_objecte_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2023/12/29 16:55:09', max_length=255),
        ),
    ]
