# Generated by Django 4.2.3 on 2024-01-18 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_object_3d_initial_objecte_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(blank=True, max_length=225, null=True)),
                ('dotsCol', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('modelCol', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('rotation', models.CharField(blank=True, max_length=225, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('initial_objecte_id', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2024/01/18 09:59:53', max_length=255),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='linePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_point', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContiPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conti_point', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
