# Generated by Django 4.2.3 on 2024-01-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_drawobject_alter_initialobject_name_point_linepoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2024/01/18 10:01:43', max_length=255),
        ),
    ]
