# Generated by Django 4.2.3 on 2024-01-18 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_initialobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contipoint',
            name='draw_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contiPoint', to='mainapp.drawobject'),
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2024/01/18 10:38:32', max_length=255),
        ),
        migrations.AlterField(
            model_name='linepoint',
            name='draw_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linePoint', to='mainapp.drawobject'),
        ),
        migrations.CreateModel(
            name='SquarePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='squarePoint', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recPoint', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolygonPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polygonPoint', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CirclePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circlePoint', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arcPoint', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
