# Generated by Django 4.2.3 on 2024-01-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_contipoint_draw_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawobject',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2024/01/22 09:00:55', max_length=255),
        ),
        migrations.CreateModel(
            name='OvalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.CharField(blank=True, max_length=225, null=True)),
                ('draw_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ovalPoint', to='mainapp.drawobject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
