# Generated by Django 4.2.3 on 2024-01-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_drawobject_order_alter_initialobject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawobject',
            old_name='initial_objecte_id',
            new_name='initial_object_id',
        ),
        migrations.AlterField(
            model_name='initialobject',
            name='name',
            field=models.CharField(default='2024/01/26 14:12:22', max_length=255),
        ),
    ]
